services:
  pg:
    image: postgres:18.1-alpine3.23
    volumes:
      - ./data/pg:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_tracker


  web:
    image: docker.io/library/tss-web
    env_file: ./apps/tss-web/.env.prod
    build:
      context: ./
      dockerfile: ./apps/tss-web/Dockerfile
    ports:
      - 3000:3000
    secrets:
      - source: env
        target: env

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222" # monitoring
    command: "--http_port 8222"
  pg-http-proxy-rs:
    image: xmadfox/pg-http-proxy-rs:0.1.3
    profiles: ["serverless"]
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@pg:5432/issue_tracker
      AUTH_TOKENS: dev
      BIND_ADDR: 0.0.0.0:8080

secrets:
  env:
    file: ./apps/tss-web/.env.prod
