services:
  pg:
    image: postgres:17.5
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_tracker

  pg-http-proxy-rs:
    image: xmadfox/pg-http-proxy-rs:0.1.3
    profiles: ["serverless"]
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@pg:5432/issue_tracker
      AUTH_TOKENS: dev
      BIND_ADDR: 0.0.0.0:8080
